### ISSUE TITLE
Bigdl2.0 migration plan for ray/automl/orca.automl/chronos

### ISSUE THREAD

**Issue by shanyu-sys** [intel/analytics-zoo#114]
# Overall plan 
 
The migration plan for ray/automl is
- `ray` will be put into `orca`.

- `automl` will be integrate with `orca.automl` (part with `chronos`).

And the pip install dependency for `chronos` will be `orca` only.

Therefore, the overall migration plan could be divided into two steps to reduce error and avoid confliction, the first step is to clean up the code structure for `orca.automl` and `chronos`, note that `automl` will be removed. And the second step is to migrate `zoo.ray`, `zoo.orca.automl` and `zoo.chronos` to BigDL2.0.

# (Ordered) task list 
#### Move to chronos

- [x] zoo/automl/pipeline/base -> zoo/chronos/pipeline  intel-analytics/analytics-zoo#4633
- [x] zoo/automl/regression/base -> zoo/chronos/regression  intel-analytics/analytics-zoo#4633
- [x] zoo/automl/recipe/base -> zoo/chronos/config  intel-analytics/analytics-zoo#4633

#### Internal clean up 

- [x] zoo/automl/common/metrics -> zoo/automl/metrics intel-analytics/analytics-zoo#4636 
- [x] zoo/automl/search/ray_tune_search_engine ->  zoo/automl/search/ray_tune intel-analytics/analytics-zoo#4648
- [x] zoo/automl/logger/tensorboardxlogger.py -> zoo/automl/search intel-analytics/analytics-zoo#4650
- [x] zoo/automl/common/utils -> zoo/automl/search, `utils.py` needs refactor intel-analytics/analytics-zoo#4641 
- [x] zoo/automl/common/parameters -> zoo/automl/search   intel-analytics/analytics-zoo#4642

#### Step 2: Move to orca.automl

- [x] zoo/automl/metrics -> zoo/orca/automl intel-analytics/analytics-zoo#4661
- [x] zoo/automl/model -> zoo/orca/automl intel-analytics/analytics-zoo#4667 
- [x] zoo/automl/search -> zoo/orca/automl intel-analytics/analytics-zoo#4670
- [x] remove zoo/automl  intel-analytics/analytics-zoo#4680 

### Chronos

- [x] chronos/model/forecast -> chronos/forecaster intel-analytics/analytics-zoo#4651 
- [x] chronos/model/anomaly -> chronos/anomaly intel-analytics/analytics-zoo#4669 

 Below tasks are part of `AutoTSTrainer` deprecation (issue intel-analytics/analytics-zoo-internal#109)

- [ ] add deprecated warning in code/docs for `AutoTSTrainer` and `TSPipeline`  intel-analytics/analytics-zoo#4786 
- [ ] chronos/autots/experimental -> chronos/autots  intel-analytics/analytics-zoo#4786 
- [ ] chronos/autots/forecast.py -> chronos/autots/deprecated  intel-analytics/analytics-zoo#4786 
- [ ] chronos/pipeline -> chronos/autots/deprecated  intel-analytics/analytics-zoo#4786 
- [ ] chronos/regression -> chronos/autots/deprecated  intel-analytics/analytics-zoo#4786 
- [ ] chronos/config -> chronos/autots/deprecated  intel-analytics/analytics-zoo#4786 
- [ ] chronos/feature -> chronos/autots/deprecated intel-analytics/analytics-zoo#4786 
- [ ] chronos/preprocessing -> chronos/autots/deprecated intel-analytics/analytics-zoo#4786 

## Step 2: Migrate to BigDL 2.0
We will split into small features and migrated to BigDL2.0 separately.

- [x] zoo/ray -> bigdl/orca/ray
- [x]  zoo/orca/automl -> bigdl/orca/automl
- [ ] zoo.chronos -> bigdl.chronos (needs to wait till `orca` has been migrated)

Note that we will **not** keep git history when migrating to `BigDL2.0`.
