### ISSUE TITLE
Some enhancemenents for Chronos Prophet & ARIMA model:

### ISSUE THREAD

**Issue by PeterQiu0516** [intel/analytics-zoo#230]
Some enhancemenents for Chronos Time Series Prophet / ARIMA model:

## Overall
- [x] Add related API docs for ARIMA and Prophet
  - Resolved in intel-analytics/analytics-zoo#4163

## ARIMA
- [x] Integrate ARIMA model (both base model, forecaster and autoestimator) for Chronos AutoTS prediction
  - Resolved in intel-analytics/analytics-zoo#3986
- [x] Refactor [`AutoARIMA.py`](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/chronos/autots/model/AutoProphet.py) to `auto_arima.py` to keep consistent with other models.
  - Resolved in intel-analytics/analytics-zoo#3986
- [x] Fix LU Decomposition Error from Randomization (#4170) for ARIMA model
  - Workaround in intel-analytics/analytics-zoo#4175
- [ ] Support `update=True, rolling=False` for ARIMA model `predict()` API (will also need to revise Unittest) (TBD)

## Prophet
- [x] Implement Prophet Forecaster and create the corresponding Unit-test.
  - Resolved in intel-analytics/analytics-zoo#4134
- [x] Update Prophet Stock Prediction Use-case notebook to use Prophet Forecaster instead of base model
  - Resolved in intel-analytics/analytics-zoo#3967
- [x] Refactor AutoProphet API following comments for ARIMA API modifications in intel-analytics/analytics-zoo#3986
  - Resolved in intel-analytics/analytics-zoo#4172
- [x] Refactor [`AutoProphet.py`](https://github.com/intel-analytics/analytics-zoo/blob/master/pyzoo/zoo/chronos/autots/model/AutoProphet.py) to `auto_prophet.py` to keep consistent with other models.
  - Resolved in intel-analytics/analytics-zoo#4172
- [x] Refactor & Update Prophet Base Model following comments for ARIMA API modifications in intel-analytics/analytics-zoo#3986
  - Resolved in intel-analytics/analytics-zoo#4195
