### ISSUE TITLE
Orca Estimator checklist

### ISSUE THREAD

**Issue by cyita** [intel/analytics-zoo#505]
- [x] Unify get model intel-analytics/analytics-zoo-internal#466
- [x] Unify save & load intel-analytics/analytics-zoo-internal#471 
- [x] Unify fit intel-analytics/analytics-zoo-internal#470 
- [x] Unify predict intel-analytics/analytics-zoo-internal#469
- [x] Unify evaluate intel-analytics/analytics-zoo-internal#467
