### ISSUE TITLE
[BigDL-2.0]Umbrella issues for chronos and orca.automl migration

### ISSUE THREAD

**Issue by shanyu-sys** [intel/analytics-zoo#62]
- [x] intel-analytics/analytics-zoo-internal#67  
- [x] intel-analytics/analytics-zoo-internal#66
- [ ] intel-analytics/analytics-zoo-internal#65 
- [ ] intel-analytics/analytics-zoo-internal#64 
- [ ] intel-analytics/analytics-zoo-internal#63
