### ISSUE TITLE
[BigDL-2.0]Chronos ongoing PR list

### ISSUE THREAD

**Issue by shanyu-sys** [intel/analytics-zoo#75]
I plan to start chronos code migration from 9/30.
Below is the ongoing chronos PR list. Note that PRs haven't been merged before migration should be backported to bigdl-2.0 branch manually.

UT:

- [x] intel-analytics/analytics-zoo#4850

example

- [x] intel-analytics/analytics-zoo#4855
- [x] intel-analytics/analytics-zoo#4703

notebook：

- [x] intel-analytics/analytics-zoo#4838
