### ISSUE TITLE
umbrella issue for automl FeatureTransformer

### ISSUE THREAD

**Issue by shanyu-sys** [intel/analytics-zoo#813]
- [ ] intel-analytics/analytics-zoo-internal#815 
- [ ] intel-analytics/analytics-zoo-internal#814 
- [x] intel-analytics/analytics-zoo-internal#969 
- [ ] intel-analytics/analytics-zoo#1763
- [ ] intel-analytics/analytics-zoo-internal#929
