### ISSUE TITLE
umbrella issue for automl code refactor 

### ISSUE THREAD

**Issue by shane-huang** [intel/analytics-zoo#847]
Umbrella Issue to enclose all AutoML related code refactor issues. 

- [x] intel-analytics/analytics-zoo-internal#877 
- [x] intel-analytics/analytics-zoo-internal#859
- [ ] intel-analytics/analytics-zoo-internal#924
- [ ] intel-analytics/analytics-zoo-internal#871
- [ ] intel-analytics/analytics-zoo-internal#872 
- [x] intel-analytics/analytics-zoo-internal#874
- [ ] intel-analytics/analytics-zoo-internal#895
- [x] intel-analytics/analytics-zoo-internal#817
