### ISSUE TITLE
[BIGDL 2.0] umbrela issue for orca migration

### ISSUE THREAD

**Issue by yangw1234** [intel/analytics-zoo#92]
- [x] intel-analytics/analytics-zoo-internal#98 
- [x] intel-analytics/analytics-zoo-internal#97 
- [x] intel-analytics/analytics-zoo-internal#94 
- [x] intel-analytics/analytics-zoo-internal#85
- [x] intel-analytics/analytics-zoo-internal#86
- [x] intel-analytics/analytics-zoo-internal#81
- [x] intel-analytics/analytics-zoo-internal#87 
- [x] intel-analytics/analytics-zoo-internal#95 
- [x] intel-analytics/analytics-zoo-internal#78 
- [x] intel-analytics/analytics-zoo-internal#96 
- [x] intel-analytics/analytics-zoo-internal#74 
- [ ] intel-analytics/analytics-zoo-internal#76 
- [x] intel-analytics/analytics-zoo-internal#72 
- [x] intel-analytics/analytics-zoo-internal#59 
- [ ] intel-analytics/analytics-zoo-internal#58 

nice to have:
- [ ] intel-analytics/analytics-zoo-internal#93
- [x] intel-analytics/analytics-zoo-internal#83
